<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>comment</key>
    <string>Nimrod Language Syntax Highlighting for Sublime Text</string>
    <key>fileTypes</key>
    <array>
        <string>nim</string>
    </array>
    <key>name</key>
    <string>Nimrod</string>
    <key>patterns</key>
    <array>
        <dict>
            <key>match</key>
            <string>#.*$\n?</string>
            <key>name</key>
            <string>comment.line.number-sign.nimrod</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\b(0x\h+('(i|u)(4|8|16|32|64))?)\b</string>
            <key>name</key>
            <string>constant.numeric.integer.hexadecimal.nimrod</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\b(0o\h+('(i|u)(4|8|16|32|64))?)\b</string>
            <key>name</key>
            <string>constant.numeric.integer.octal.nimrod</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\b(([1-9]+[0-9]*\.(?=[^.])[0-9]*)|(0\.(?=[^.])[0-9]*))</string>
            <key>name</key>
            <string>constant.numeric.float.nimrod</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\b([1-9]+[0-9]*|0)('(u|U|i|I)(8|16|32|64)?)?\b</string>
            <key>name</key>
            <string>constant.numeric.integer.decimal.nimrod</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\b(int|int8|int16|int32|int64|uint|uint8|uint16|uint32|uint64|float|float32|float64|bool|char|string|cstring|pointer|range|array|openarray|varargs|seq|set|tuple|cchar|cshar|cshort|cint|csize|clong|clonglong|cfloat|cdouble|clongdouble|cuchar|cushort|cuint|culong|culonglong)\b</string>
            <key>name</key>
            <string>support.type.nimrod</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\b(var|enum|const|type|object|ref|ptr)\b</string>
            <key>name</key>
            <string>storage.modifier.nimrod</string>
        </dict>
        <dict>
            <key>comment</key>
            <string>keywords that delimit flow blocks or alter flow from within a block</string>
            <key>match</key>
            <string>\b(elif|else|for|if|try|while|when|break|continue|raise|return|yield|case|except)\b</string>
            <key>name</key>
            <string>keyword.control.flow.nimrod</string>
        </dict>
        <dict>
            <key>name</key>
            <string>string.quoted.double.nimrod</string>
            <key>begin</key>
            <string>"</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.begin.nimrod</string>
                </dict>
            </dict>
            <key>end</key>
            <string>"</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.end.nimrod</string>
                </dict>
            </dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#escaped_char</string>
                </dict>
            </array>
        </dict>
        <dict>
            <key>name</key>
            <string>string.quoted.single.nimrod</string>
            <key>begin</key>
            <string>'</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.begin.nimrod</string>
                </dict>
            </dict>
            <key>end</key>
            <string>'</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.end.nimrod</string>
                </dict>
            </dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#escaped_char</string>
                </dict>
            </array>
        </dict>
        <dict>
            <key>name</key>
            <string>keyword.operator.comparison.nimrod</string>
            <key>match</key>
            <string>&lt;\=|&gt;\=|\=\=|&lt;|&gt;|\!\=|\=~</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\=</string>
            <key>name</key>
            <string>keyword.operator.assignment.nimrod</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(\b(and|or|not|xor|shl|shr|div|mod|in|notin|is|isnot|of)\b|(=|\+|-|\*|/|&lt;|&gt;|@|\$|~|&amp;|%|!|\?|\^|\.\.|\.|:|\\)+)</string>
            <key>name</key>
            <string>keyword.operator.nimrod</string>
        </dict>
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>keyword.control.import.nimrod</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>keyword.control.import.from.nimrod</string>
                </dict>
            </dict>
            <key>match</key>
            <string>\b(?:(import)|(from))\b</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\b(addr|assert|mod|repr|map|defined|definedInScope|compiles|low|high|sizeOf|is|of|echo|shallowCopy|getAst|let|cast|quit)\b</string>
            <key>name</key>
            <string>support.function.builtin.nimrod</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\b(proc)\b</string>
            <key>name</key>
            <string>storage.type.function.nimrod</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\b(iterator)\b</string>
            <key>name</key>
            <string>storage.type.iterator.nimrod</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\b(converter)\b</string>
            <key>name</key>
            <string>storage.type.function.nimrod</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\b(template)\b</string>
            <key>name</key>
            <string>storage.type.template.nimrod</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\b(macro)\b</string>
            <key>name</key>
            <string>storage.type.macro.nimrod</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\b(method)\b</string>
            <key>name</key>
            <string>storage.type.method.nimrod</string>
        </dict>
        <dict>
            <key>name</key>
            <string>constant.language.nimrod</string>
            <key>match</key>
            <string>\b(nil|true|false)\b</string>
        </dict>
        <dict>
            <key>name</key>
            <string>invalid.illegal.name.nimrod</string>
            <key>match</key>
            <string>\b(addr|and|as|asm|atomic|assert|bind|block|break|case|cast|const|continue|converter|discard|distinct|div|do|elif|else|end|enum|except|export|finally|for|from|generic|if|import|in|include|interface|is|isnot|iterator|lambda|let|macro|method|mixin|mod|nil|not|notin|object|of|or|out|proc|ptr|raise|ref|return|shared|shl|shr|static|template|try|tuple|type|var|when|while|with|without|xor|yield)\b</string>
        </dict>
    </array>
    <key>repository</key>
    <dict>
        <key>escaped_char</key>
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>constant.character.escape.hex.nimrod</string>
                </dict>
                <key>10</key>
                <dict>
                    <key>name</key>
                    <string>constant.character.escape.linefeed.nimrod</string>
                </dict>
                <key>11</key>
                <dict>
                    <key>name</key>
                    <string>constant.character.escape.return.nimrod</string>
                </dict>
                <key>12</key>
                <dict>
                    <key>name</key>
                    <string>constant.character.escape.tab.nimrod</string>
                </dict>
                <key>13</key>
                <dict>
                    <key>name</key>
                    <string>constant.character.escape.vertical-tab.nimrod</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>constant.character.escape.escape.nimrod</string>
                </dict>
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>constant.character.escape.newline.nimrod</string>
                </dict>
                <key>4</key>
                <dict>
                    <key>name</key>
                    <string>constant.character.escape.backlash.nimrod</string>
                </dict>
                <key>5</key>
                <dict>
                    <key>name</key>
                    <string>constant.character.escape.double-quote.nimrod</string>
                </dict>
                <key>6</key>
                <dict>
                    <key>name</key>
                    <string>constant.character.escape.single-quote.nimrod</string>
                </dict>
                <key>7</key>
                <dict>
                    <key>name</key>
                    <string>constant.character.escape.bell.nimrod</string>
                </dict>
                <key>8</key>
                <dict>
                    <key>name</key>
                    <string>constant.character.escape.backspace.nimrod</string>
                </dict>
                <key>9</key>
                <dict>
                    <key>name</key>
                    <string>constant.character.escape.formfeed.nimrod</string>
                </dict>
            </dict>
            <key>match</key>
            <string>(\\x[0-9A-F]{2})|(\\e)|(\\n)|(\\\\)|(\\\")|(\\')|(\\a)|(\\b)|(\\f)|(\\l)|(\\r)|(\\t)|(\\v)</string>
        </dict>
    </dict>
    <key>scopeName</key>
    <string>source.nimrod</string>
    <key>uuid</key>
    <string>f0da69cf-e5b2-4311-a18c-d39c75f60e86</string>
</dict>
</plist>
